travis:
  secure:
    BINSTAR_TOKEN: iUIaBYrSWQb6muulk0qJQ/gy8IPNQZWxHuMu0FyYLf1RIZPA8S3HW9lG7OYreEmF2ra9kZsS1lO0fsKg7C69lF7vcZGs0GXGrCD1iCvstgHmiLne+Udk4XQw/SHvOY6P8WiZDYiEEwd9ll53DOcAYcDNRWhUUMQn1j2/nSdZ2cFP5MBbS2XUqukq6srumqbHl3rWc0gqB616cNIDxup+r+qjOilOG5W3vOS0NCkeCCSkNIOkFJN75SyS5muVG/9fdQ7HOnDKFG99Kfe1fAwiCPGx2wgNtkjuXxWmTCkdPe/nM21PXMz76RxZwo8hrTPURMjiQs6JEJmoqwKLYdWNfkuA5+bEORGR6e5p/dQoXfwJABewMgyNdKHlRGyfyiloJQQ85IsJWjQWtZJwAKjwG9PKlcJlrACSd0gO6QCNDaG8VLb6KO9aM6HcJNsZ+Q+tF1rAbTgzF8zFeTojBLFku5Lzoo2OnDFpKTNe60CMnajz07J7G0EMvSJGeyZhlhis4YwreTJxdtm4VuSYAxEZOB3NWrBQK0wW/kUpLKEHCVnPTTUpEiC2A1bt6N+0jOuxxZ0aer2Zjvr0JG7vcQQvaSA3TrQvAWmoMsrGvgZdaEwKNGEV+g9QYHiOC1qe58CKR4mQ/C02Nf4s7ZrhRYmIyABgcXmsgcl1XSItOB0TluM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
