travis:
  secure:
    BINSTAR_TOKEN: W8qUapXTpEH9dMrAy3NL/hMtVFq1k2qqY5yUXG0UFg+k+NeD3nSZNl3bvhZzNf9mCCxGsTSMHRWT44pY38xKjIERdxUpSaWv7iRcmhc8LavU3jOQKMmxG7/PjdsBrbNHjwfWrSjTSI5cbs4tqQ8eK5vY7MclF+k+SPBMAaZ3zJu88K9PZmOGsda6me0vKYwAv68X/8vnCMOxC065yiciZJHiH/h5h5L8ru28pIDsxCKCUgpFbUHByQSmdvIkhmkRKMxfCTZL3U/hXyzmb9ca/+EeXIicC/mZwP44fLJg8jlGiSA9h4h4T/CBgTMugKsb6PMeaU9HKWGLjAT2YfmLvPjY2ieKL6wW30eQ7IPxVNmcDt6GU1CGy8nWgKmsHqPCSuj3pT6pAx4WyIpTTKp0kPds5S+hpt9Q8mMF2F1yudiqMyDUICfx2a2wbf3g+gzQ98Rvu7eGckXZSTTkd/cEXEEEzUJCU4iiq/vEOqTn1WGxOgy4CVDDb6Gx4L16XzwfrM4fw68OtyjLs0y8TjMJDtHmpXHZ4r3gu38fS7muyAgAITkMP1m/OLPxBlTG8Ahrq5QhR/IrNjr9G7kiuuVCJr7LQGrDuFDCJ9tdqkAFVqSgRYyPzTdcqZyQGx/tiAyz8f3+bVAMaDuYzuloupQixDw4scQBfb6oWo7w6hZsq0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
